# YAML is case sensitive
apiVersion: apps/v1  # specify api to use for deployment
kind: Deployment  # kind of service/object you want to create
metadata:
  name: sparta-nodejs-app-deployment # name the deployment
spec:
  selector:
    matchLabels:
      app: sparta-nodejs-app  # look for this label/tag to match with k8 service
  # create a replica set of this with instances/pods
  replicas: 3
  template:
    metadata:
      labels:
        app: sparta-nodejs-app # this label connects the deployment to the service
    spec:
      containers:
      - name: sparta-nodejs-app-container
        image: riverstallions/sparta-app-image-for-k8s-use:1.0 # the image you created to run nginx in a container
        ports:
        - containerPort: 3000 # port to expose in the container