---
apiVersion: v1
kind: Service
metadata:
  name: sparta-nodejs-app-svc
  namespace: default
spec:
  ports: # access the service on port 30001
  - nodePort: 31704 # range is 30000-32768
    port: 3000
    targetPort: 3000
 
  selector:
    app: sparta-nodejs-app  # this label connect this service to the deployment
  type: NodePort  # also use LoadBalancer - for local use cluster IP