apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: default
spec:
  selector:
    app: db  # this label connects this service to the deployment
  ports:
  - protocol: TCP
    port: 27017 # service's own internal port
    targetPort: 27017 # port that db listens on inside the db deployment pod - needs to match containerPort in the deployment yml file
