---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
spec:
  ports: # access the service on port 30001
  - nodePort: 30001 # range is 30000-32768
    port: 80
    targetPort: 80
 
  selector:
    app: nginx  # this label connect this service to the deployment
  type: NodePort  # also use LoadBalancer - for local use cluster IP